/* English strings. Same keys as es.js; if one is missing, the Spanish text is shown. */
(window.I18N_CATALOGS = window.I18N_CATALOGS || {}).en = {
  "meta.graphikosmos": "Graphikosmos",
  "ui.selecciona_el_concepto_a_fusionar": "<span class=\"w-1.5 h-1.5 rounded-full bg-fuchsia-400 animate-pulse\"></span> Select the concept to merge",
  "ui.cancelar": "Cancel",
  "ui.procesando_informacion": "Processing information...",
  "ui.toca_el_nodo_destino": "<span class=\"w-1.5 h-1.5 rounded-full bg-amber-400 animate-pulse\"></span> Tap the target node",
  "ui.2_nodos_seleccionados": "2 nodes selected",
  "ui.convertir_en_subesquema": "📦 Convert to sub-map",
  "ui.volver": "← Back",
  "ui.graphikosmos": "Graphikosmos",
  "ui.crea_un_solo_nodo_en": "Creates a single node on the canvas with exactly what you type here. To generate a full map from a topic, a long text or a web page link, use Reader Mode.",
  "ui.escribe_algo_y_crea_un": "Type something to create a new node with it...",
  "ui.generar": "Generate",
  "ui.iniciar_sesion": "Sign in",
  "ui.ver_mis_esquemas_guardados_automaticamente": "See my automatically saved maps",
  "ui.mis_proyectos": "My Projects",
  "ui.descargar_esquema": "Download map",
  "ui.capturar": "Capture",
  "ui.enviar_un_comentario_o_sugerencia": "Send a comment or suggestion",
  "ui.sugerencias": "Feedback",
  "ui.ocultar_modo_lector": "<span>📖</span> Hide Reader Mode",
  "ui.generar_crea_un_nodo_suelto": "💡 \"Generate\" creates a single node · For a full map (topic, long text or link), use Reader Mode",
  "ui.como_se_acomodan_las_ramas": "How branches are arranged when generating a new map",
  "ui.modo": "Mode:",
  "ui.arbol": "🌳 Tree",
  "ui.sistema_solar": "🪐 Solar system",
  "ui.deshacer_la_ultima_accion_ctrl": "Undo the last action (Ctrl/Cmd+Z)",
  "ui.deshacer": "Undo",
  "ui.buscar_un_nodo_ctrl_cmd": "Search for a node (Ctrl/Cmd+K)",
  "ui.buscar": "Search",
  "ui.modo_foco_resalta_los_conceptos": "Focus mode: highlights the most connected concepts in the map",
  "ui.modo_foco": "Focus mode",
  "ui.modo_presentacion_oculta_toda_la": "Presentation mode: hides the whole interface and leaves only the canvas",
  "ui.presentacion": "Presentation",
  "ui.descargar_un_informe_rtf_del": "Download a report (.rtf) of the current map",
  "ui.informe": "Report",
  "ui.sonido_al_crear_nodos_encendido": "Sound when creating nodes: on",
  "ui.limpiar": "<span>🧹</span> Clear",
  "ui.salir_de_presentacion": "✕ Exit presentation",
  "ui.siguiente_lugar_del_recorrido": "Next stop on the tour",
  "ui.nodo_anterior": "Previous node",
  "ui.pausar_reanudar": "Pause / resume",
  "ui.siguiente_nodo": "Next node",
  "ui.salir_del_recorrido_esc": "Exit the tour (Esc)",
  "ui.salir_del_quiz_esc": "Exit the quiz (Esc)",
  "ui.buscar_un_nodo_por_su": "Search for a node by its text...",
  "ui.modo_lector": "📖 Reader Mode",
  "ui.importar_un_pdf_se_extrae": "Import a PDF (its text is extracted into the editor below, keeping the formatting as close as possible; you can choose which pages)",
  "ui.subir_pdf": "Upload PDF",
  "ui.abrir_otro_lector_otro_esquema": "Open another reader (a separate map)",
  "ui.limpiar_texto_y_contexto": "Clear text and context",
  "ui.cerrar": "Close",
  "ui.documento_pdf": "document.pdf",
  "ui.paginas": "Pages",
  "ui.de": "to",
  "ui.cargar": "Load",
  "ui.generar_esquema": "🌐 Generate Map",
  "ui.analiza_el_texto_su_argumentacion": "Analyzes the text (its argumentation, structure, etc.) instead of just structuring what it says",
  "ui.analizar_texto": "🔎 Analyze Text",
  "ui.contexto": "📎 Context:",
  "ui.editar": "edit",
  "ui.detectado_automatico_o_escribelo_tu": "Auto-detected, or type it yourself...",
  "ui.negrita": "Bold",
  "ui.cursiva": "Italic",
  "ui.subrayado": "Underline",
  "ui.titulo_grande": "Large heading",
  "ui.titulo_mediano": "Medium heading",
  "ui.parrafo_normal": "Normal paragraph",
  "ui.lista_con_vinetas": "Bulleted list",
  "ui.lista_numerada": "Numbered list",
  "ui.tamano_de_letra": "Font size",
  "ui.pequeno": "Small",
  "ui.normal": "Normal",
  "ui.grande": "Large",
  "ui.muy_grande": "Very large",
  "ui.quitar_formato": "Clear formatting",
  "ui.reducir_el_tamano_de_todo": "Decrease the size of all reader text",
  "ui.aumentar_el_tamano_de_todo": "Increase the size of all reader text",
  "ui.pega_aqui_un_texto_o": "Paste a text or <span class=\"text-indigo-600 font-semibold\">a link</span> here",
  "ui.crear_elemento_en_esquema": "⚡ Create element in map",
  "ui.vincular_a_nodo": "🔗 Link to node...",
  "ui.pega_un_texto_un_enlace": "Paste a text, a link, or upload a PDF — we'll build your map and walk you through it step by step, one idea at a time.",
  "ui.subir_un_pdf": "Upload a PDF",
  "ui.se_usan_las_primeras_paginas": "The first pages of the PDF are used.",
  "ui.crear_mi_esquema": "Create my map",
  "ui.graphikosmos_esta_pensado_para_usarse": "Graphikosmos is designed for computers — this is a simplified view for exploring from your phone.",
  "ui.hablemos_del_campo_de_estudio": "Let's talk about the field you want to explore",
  "ui.un_tema_de_la_universidad": "A university subject, something from work, or pure curiosity — we'll build your first map from it.",
  "ui.ej_la_revolucion_francesa_computacion": "E.g.: The French Revolution, Quantum Computing...",
  "ui.siguiente": "Next →",
  "ui.ya_tengo_un_texto_un": "I already have a text, a link or a PDF",
  "ui.probar_con_un_tema_al": "Try a random topic, no questions",
  "ui.para_que_lo_estudias": "What are you studying it for?",
  "ui.cambia_el_enfoque_con_el": "This changes the approach we use to build your text and your map.",
  "ui.preparar_un_examen_o_un": "Preparing for an exam or a course",
  "ui.una_tesis_o_una_investigacion": "A thesis or research project",
  "ui.ensenarlo_a_otras_personas": "Teaching it to others",
  "ui.mi_trabajo_o_mi_profesion": "My job or profession",
  "ui.curiosidad_personal": "Personal curiosity",
  "ui.atras": "← Back",
  "ui.que_otras_areas_te_interesan": "What other areas interest you?",
  "ui.elegi_hasta_3_buscamos_como": "Pick up to 3. We'll look for how they connect with your field.",
  "ui.buscar_un_area": "Search for an area...",
  "ui.que_tanto_conoces_del_tema": "How much do you know about the topic?",
  "ui.asi_ajustamos_que_tan_tecnico": "This is how we adjust how technical the text is.",
  "ui.estoy_empezando": "I'm just starting",
  "ui.conozco_lo_basico": "I know the basics",
  "ui.tengo_bastante_base": "I have a solid foundation",
  "ui.que_duda_o_pregunta_te": "What question or doubt intrigues you?",
  "ui.opcional_si_la_escribis_la": "Optional. If you write it, we'll answer it inside your text.",
  "ui.crear_mi_esquema_2": "Create my map →",
  "ui.que_queres_estudiar": "What do you want to study?",
  "ui.pega_un_texto_un_enlace_2": "Paste a text, a link or upload a PDF, and we'll build the map from it.",
  "ui.generando_tu_primer_esquema": "Generating your first map",
  "ui.lo_hacemos_a_partir_de": "We build it from a text I'm generating for you right now. Later you'll be able to use any text you like: pasted, a link or a PDF.",
  "ui.esto_es_un_ejemplo_de": "This is an example of how Graphikosmos works",
  "ui.armamos_este_esquema_a_partir": "We built this map from your answers. The text was generated by an AI just for this example, so verify the facts before quoting it. Whenever you want, paste your own text, a link or a PDF in Reader Mode.",
  "ui.entendido": "Got it",
  "ui.argumentativo_critico": "Argumentative / critical",
  "ui.tesis_argumentos_evidencia_supuestos_objeciones": "Thesis, arguments, evidence, assumptions, objections",
  "ui.academico_de_investigacion": "Academic / research",
  "ui.pregunta_metodologia_hallazgos_limitaciones_conclusiones": "Question, methodology, findings, limitations, conclusions",
  "ui.literario": "Literary",
  "ui.tema_estructura_narrativa_estilo_voz": "Theme, narrative structure, style, voice, symbols",
  "ui.retorico_persuasivo": "Rhetorical / persuasive",
  "ui.proposito_audiencia_estrategias_tono": "Purpose, audience, strategies, tone",
  "ui.comparativo_de_posturas": "Comparison of positions",
  "ui.posiciones_en_tension_fundamentos_acuerdos": "Positions in tension, foundations, agreements/disagreements",
  "ui.otro_tipo_de_analisis": "Another type of analysis...",
  "ui.ir": "Go",
  "ui.ver_definicion": "View definition",
  "ui.explicacion_sencilla": "Simple explanation",
  "ui.prompt_personalizado": "Custom prompt",
  "ui.explorar": "Explore",
  "ui.generar_esquema_completo_a_partir": "Generate a full map from here",
  "ui.editar_2": "Edit",
  "ui.expandir_subesquema": "Expand sub-map",
  "ui.enlazar": "Connect",
  "ui.vincular_con": "Link with...",
  "ui.generar_sinergia_con": "Generate Synergy with...",
  "ui.ver_en_el_texto": "See in the text",
  "ui.conceptos_relacionados": "Related Concepts",
  "ui.cuestionar_antitesis": "Question / Antithesis",
  "ui.ponme_a_prueba": "Test me",
  "ui.ejemplos_practicos": "Practical Examples",
  "ui.analisis_de_lagunas_conceptuales": "Concept gap analysis",
  "ui.eliminar": "Delete",
  "ui.amplia_tu_cosmos": "Expand your Cosmos",
  "ui.con_gusto_te_ayudamos_a": "We'll gladly help you keep building maps.",
  "ui.contactanos_para_seguir_usando_la": "Contact us to keep using the app",
  "ui.escribenos_un_momento_y_seguimos": "Write to us for a moment and we'll keep building your cosmos of ideas together.",
  "ui.escribir_por_whatsapp": "Write via WhatsApp",
  "ui.o_te_escribimos_nosotros": "or we write to you",
  "ui.tu_correo": "Your email",
  "ui.enviar": "Send",
  "ui.tambien_podes_escribirnos_directo_a": "You can also write to us directly at",
  "ui.alguna_idea_o_comentario": "Any idea or comment?",
  "ui.leemos_todo_nos_ayuda_a": "We read everything — it helps us improve Graphikosmos.",
  "ui.tu_correo_opcional_si_queres": "Your email (optional, if you want us to reply)",
  "ui.gracias_ya_lo_leimos": "Thank you! We've read it.",
  "ui.continua_explorando": "Keep exploring",
  "ui.para": "To",
  "ui.continuar_explorando": "keep exploring",
  "ui.inicia_sesion_gratis_guardaremos_tu": ", sign in for free. We'll save your progress in the cloud and unlock your ",
  "ui.50_nodos_de_bienvenida": "50 welcome nodes",
  "ui.iniciar_sesion_registrarse": "Sign in / Sign up",
  "ui.tus_mapas_guardados_en_la": "Your maps saved in the cloud.",
  "ui.rango_intelectual": "Intellectual Rank",
  "ui.explorador_conceptual": "Concept Explorer",
  "ui.mapas": "Maps",
  "ui.conceptos": "Concepts",
  "ui.no_tienes_proyectos_guardados_aun": "You don't have any saved projects yet.",
  "ui.crear_nuevo_esquema_en_blanco": "<span>✨</span> Create New Blank Map",
  "ui.guia_rapida_de_graphikosmos": "Graphikosmos Quick Guide",
  "ui.domina_todas_las_herramientas_de": "Master all the synthesis and visual mapping tools.",
  "ui.controles_del_lienzo": "<span>🖱️</span> Canvas Controls",
  "ui.mover_el_lienzo": "• Move the canvas:",
  "ui.arrastra_el_fondo_vacio_con": "Drag the empty background with the left click to pan around the map.",
  "ui.zoom": "• Zoom:",
  "ui.usa_la_rueda_del_mouse": "Use the mouse wheel to zoom in or out.",
  "ui.mover_un_nodo": "• Move a node:",
  "ui.arrastralo_directamente_con_clic_izquierdo": "Drag it directly with the left click; it stays fixed where you drop it.",
  "ui.1_creacion_de_esquemas_3": "<span>🌐</span> 1. Creating Maps (3 Levels)",
  "ui.desde_un_tema": "From a Topic",
  "ui.si_el_lienzo_esta_vacio": "If the canvas is empty, type any topic in the top bar and press <strong>Add</strong>. A full 3-level tree will unfold automatically. (If there are already nodes on the canvas, it will be added as a single node).",
  "ui.desde_el_modo_lector": "From Reader Mode",
  "ui.pega_un_ensayo_articulo_o": "Paste an essay, article or chapter in the left panel and press <strong>Generate Map from text</strong> to structure its content faithfully in 3 levels.",
  "ui.2_menu_de_acciones_de": "<span>⚡</span> 2. Node Action Menu (Click on a node)",
  "ui.conceptos_e_incognitas": "Concepts and Mysteries",
  "ui.despliega_sub_ramas_teoricas_y": "Unfolds theoretical sub-branches and unlocks a free <strong>❓ Mystery</strong> node with a paradox or puzzle about the topic. Expand the mystery to reveal its answer.",
  "ui.cuestionar_antitesis_2": "⚡ Question / Antithesis",
  "ui.genera_pensamiento_critico_mostrando_posturas": "Generates critical thinking by showing opposing positions, theoretical limits or historical refutations of the selected concept.",
  "ui.ponme_a_prueba_2": "🧠 Test me",
  "ui.abre_un_reto_socratico_en": "Opens a Socratic challenge in the side panel. When you validate your argument, you unlock a <strong>🏆 Golden Mastery Node</strong> with your own synthesis.",
  "ui.generar_sinergia": "⚡ Generate Synergy",
  "ui.selecciona_esta_opcion_en_un": "Select this option on a node and then click a different node to discover the convergence or synthesis between both concepts.",
  "ui.prompt_personalizado_2": "✨ Custom prompt",
  "ui.escribe_una_instruccion_libre_para": "Write a free-form instruction for that node (e.g. <em>\"Explain this according to Max Weber\"</em>). A bridge node will be created with your request and its answers.",
  "ui.definiciones_interactivas": "📖 Interactive Definitions",
  "ui.usa_ver_definicion_para_leerla": "Use <strong>View definition</strong> to read it inside the node or <strong>Use definition</strong> to open it in the side panel with key concepts highlighted (click them to launch them onto the map).",
  "ui.3_extraccion_por_subrayado_y": "<span>📖</span> 3. Extraction by Highlighting and Saving",
  "ui.subrayar_en_el_lector_o": "• <strong>Highlight in the Reader or in Definitions:</strong> Select any word or phrase with the mouse inside Reader Mode or in the definition side panel to make the floating <strong>⚡ Create element in map</strong> button appear. The text will be underlined and linked to the node.",
  "ui.eliminacion_inteligente_al_borrar_un": "• <strong>Smart Deletion:</strong> When you delete a node that has descendants, the system will ask whether you also want to delete all its child sub-nodes or keep them.",
  "ui.mis_proyectos_y_captura_inicia": "• <strong>My Projects and Capture:</strong> Sign in so your maps are saved automatically in the cloud, or use the <strong>Capture</strong> button in the top bar to download your map in high resolution (PNG).",
  "js.sin_iniciar_sesion": "(not signed in)",
  "js.hola_uso_graphikosmos_y_me": "Hi, I use Graphikosmos and I'd like to keep using it. Could you tell me about the options available to continue? My account email is: {userEmail}",
  "js.enviando": "Sending...",
  "js.ya_nos_escribiste_varias_veces": "You've written to us several times in a row — give us a moment to reply.",
  "js.no_se_pudo_enviar_intenta": "Could not send. Try again in a few minutes.",
  "js.no_se_pudo_enviar_revisa": "Could not send. Check your connection and try again.",
  "js.listo_te_vamos_a_escribir": "Done! We'll write to that email address.",
  "js.cancelar": "Cancel",
  "js.guardar": "Save",
  "js.entendido": "Got it",
  "js.analizando_jerarquia_conceptual": "Analyzing conceptual hierarchy...",
  "js.conectando_nodos_y_relaciones": "Connecting nodes and relationships...",
  "js.organizando_niveles_en_el_lienzo": "Arranging levels on the canvas...",
  "js.invitado": "Guest",
  "js.estas_generando_muy_rapido_espera": "You're generating too fast. Wait a minute and try again.",
  "js.procesar_este_esquema": "process this map",
  "js.mi_cuenta": "My Account",
  "js.iniciar_sesion": "Sign in",
  "js.nodos": "{availableNodes} Nodes",
  "js.relacionado": "related",
  "js.ya_tienes_un_esquema_en": "You already have a map on the canvas. Do you want to clear the existing canvas before generating the new one?",
  "js.limpiar_el_lienzo": "Clear the canvas?",
  "js.si_crear_proyecto_nuevo": "Yes, create a new project",
  "js.no_agregar_al_actual": "No, add to the current one",
  "js.estructurando_esquema": "Structuring map...",
  "js.intenta_de_nuevo_en_unos": "Try again in a few seconds.",
  "js.argumentativo_critico": "Argumentative / critical",
  "js.academico_de_investigacion": "Academic / research",
  "js.literario": "Literary",
  "js.retorico_persuasivo": "Rhetorical / persuasive",
  "js.comparativo_de_posturas": "Comparison of positions",
  "js.personalizado": "Custom",
  "js.analizando_texto": "Analyzing text ({analysisLabel})...",
  "js.escribe_un_tema_pega_un": "Type a topic, paste a text or the link to a web page in the reader.",
  "js.profundizar_en_conceptos_relacionados": "dig deeper into related concepts",
  "js.revelando_incognita": "Revealing mystery...",
  "js.responde_de_forma_clara_reveladora": "Answer this mystery in a clear, revealing and direct way: {topicName}",
  "js.no_se_pudo_resolver_la": "Could not resolve the mystery.",
  "js.se_explica_por": "is explained by",
  "js.error_al_resolver_la_incognita": "Error resolving the mystery.",
  "js.entre_3_y_5_segun": "between 3 and 5 (depending on relevance)",
  "js.generando_conceptos_relacionados": "Generating related concepts...",
  "js.no_se_pudieron_generar_conceptos": "Could not generate related concepts.",
  "js.incognita": "*❓ Mystery:*\n{question}",
  "js.plantea_duda": "raises doubt",
  "js.error_al_conectar_con_el": "Error connecting to the service.",
  "js.varios_entre_3_y_5": "several (between 3 and 5 representative ones)",
  "js.buscando_casos_practicos": "Looking for practical cases...",
  "js.no_se_pudieron_generar_ejemplos": "Could not generate examples.",
  "js.del_texto": "from the text",
  "js.calculando_convergencia": "Calculating convergence...",
  "js.no_se_pudo_generar_la": "Could not generate the synergy.",
  "js.intenta_de_nuevo_en_unos_2": "Try again in a few seconds",
  "js.generando_puente_conceptual": "Generating conceptual bridge...",
  "js.no_se_pudo_generar_el": "Could not generate the link.",
  "js.nodos_seleccionados": "{count} nodes selected",
  "js.dentro_de": "Inside: {label}",
  "js.subesquema": "Sub-map",
  "js.este_nodo_no_quedo_vinculado": "This node isn't linked to any quote in the text (it may come from a hand-written topic, not from a document).",
  "js.no_se_encontro_el_panel": "The source reading panel for this node was not found (you may have closed it).",
  "js.no_se_pudo_ubicar_la": "Could not locate the exact quote in the current text (you may have edited it).",
  "js.elige_el_nodo_o_panel": "Choose the node or panel the arrow will point to · Esc to cancel",
  "js.restaurar": "Restore",
  "js.minimizar": "Minimize",
  "js.elegi_un_archivo_pdf": "Choose a PDF file.",
  "js.leyendo_el_pdf": "Reading the PDF...",
  "js.no_se_pudo_leer_ese": "Could not read that file as a PDF (it may be damaged or password-protected).",
  "js.extrayendo_texto_de_las_paginas": "Extracting text from pages {fromPage}–{toPage}...",
  "js.no_se_encontro_texto_en": "No text was found on those pages (it may be a scanned PDF, with no real text inside the file).",
  "js.pag": "{file} (pp. {fromPage}–{toPage})",
  "js.no_se_pudo_extraer_el": "Could not extract the text from those PDF pages.",
  "js.ahora_haz_clic_en_el": "Now click the node of the map you want to link this excerpt to as a child.",
  "js.deseas_limpiar_el_texto_y": "Do you want to clear the text and context of this reader?",
  "js.involucra": "involves",
  "js.editar_texto_del_nodo": "Edit node text:",
  "js.editar_texto": "✏️ Edit text",
  "js.deriva_en": "leads to",
  "js.leyendo_la_pagina": "Reading the page...",
  "js.no_se_pudo_leer_esa": "Could not read that page.",
  "js.pega_un_texto_un_tema": "Paste a text, a topic, a link, or upload a PDF to get started.",
  "js.subir_un_pdf": "Upload a PDF",
  "js.la_paradoja_de_fermi": "The Fermi Paradox",
  "js.el_mito_de_la_caverna": "Plato's Allegory of the Cave",
  "js.computacion_cuantica": "Quantum Computing",
  "js.filosofia_estoica": "Stoic Philosophy",
  "js.neuroplasticidad": "Neuroplasticity",
  "js.inteligencia_artificial_general": "Artificial General Intelligence",
  "js.economia_conductual": "Behavioral Economics",
  "js.la_teoria_de_cuerdas": "String Theory",
  "js.imperio_romano": "The Roman Empire",
  "js.preparar_un_examen_o_un": "preparing for an exam or a course",
  "js.una_tesis_o_una_investigacion": "a thesis or a research project",
  "js.ensenarlo_a_otras_personas": "teaching it to others",
  "js.su_trabajo_o_su_profesion": "their job or profession",
  "js.curiosidad_personal": "personal curiosity",
  "js.principiante_esta_empezando": "beginner, just starting",
  "js.intermedio_conoce_lo_basico": "intermediate, knows the basics",
  "js.avanzado_tiene_bastante_base": "advanced, has a solid foundation",
  "js.historia": "History",
  "js.filosofia": "Philosophy",
  "js.psicologia": "Psychology",
  "js.sociologia": "Sociology",
  "js.antropologia": "Anthropology",
  "js.ciencia_politica": "Political science",
  "js.economia": "Economics",
  "js.derecho": "Law",
  "js.educacion": "Education",
  "js.comunicacion": "Communication",
  "js.linguistica": "Linguistics",
  "js.literatura": "Literature",
  "js.arte": "Art",
  "js.musica": "Music",
  "js.arquitectura_y_diseno": "Architecture and design",
  "js.teologia_y_religiones": "Theology and religions",
  "js.etica": "Ethics",
  "js.matematicas": "Mathematics",
  "js.estadistica": "Statistics",
  "js.fisica": "Physics",
  "js.quimica": "Chemistry",
  "js.biologia": "Biology",
  "js.medicina_y_salud": "Medicine and health",
  "js.neurociencia": "Neuroscience",
  "js.ecologia_y_ambiente": "Ecology and environment",
  "js.geografia": "Geography",
  "js.astronomia": "Astronomy",
  "js.geologia": "Geology",
  "js.computacion": "Computer science",
  "js.inteligencia_artificial": "Artificial intelligence",
  "js.ingenieria": "Engineering",
  "js.administracion_y_negocios": "Management and business",
  "js.contabilidad_y_finanzas": "Accounting and finance",
  "js.mercadeo": "Marketing",
  "js.trabajo_social": "Social work",
  "js.agricultura": "Agriculture",
  "js.pega_un_texto_o_un": "Paste a text or a link, or upload a PDF.",
  "js.este_nodo_tiene_sub_nodo": "This node has {size} connected sub-node(s).",
  "js.estos_nodos_tienen_sub_nodo": "These {length} nodes have {size} connected sub-node(s).",
  "js.eliminar_nodo_y_sus_hijos": "Delete node and its children?",
  "js.eliminar_nodos_y_sus_hijos": "Delete nodes and their children?",
  "js.eliminar_todo": "Delete all",
  "js.solo_este_nodo": "Only this node",
  "js.solo_los_marcados": "Only the selected ones",
  "js.encendido": "on",
  "js.apagado": "off",
  "js.sonido_al_crear_nodos": "Sound when creating nodes: {state}",
  "js.no_se_pudo_obtener_una": "Could not get a definition for this node.",
  "js.no_hay_nada_que_recorrer": "There is nothing to tour yet — generate a map first.",
  "js.no_hay_nada_para_el": "There is nothing for the quiz yet — generate a map first.",
  "js.vas_a_limpiar_el_lienzo": "You are about to clear the current canvas. This map has already been saved in 'My Projects'.\n\n",
  "js.deseas_que_lo_proximo_que": "Do you want whatever you do next to be saved in a NEW project, separate from this one?",
  "js.si_proyecto_nuevo": "Yes, new project",
  "js.no_seguir_en_este": "No, keep working in this one",
  "js.deseas_limpiar_el_texto_y_2": "Do you want to clear the text and context of the reading panel?",
  "js.el_lienzo_esta_vacio": "The canvas is empty.",
  "js.preparando_captura": "Preparing capture...",
  "js.error_al_exportar_la_imagen": "Error exporting the image.",
  "js.guardando": "Saving...",
  "js.guardado": "Saved",
  "js.mis_proyectos": "My Projects",
  "js.mi_esquema": "My Map",
  "js.error_al_sincronizar_en_la": "Error syncing to the cloud:",
  "js.polimata_maestro": "Master Polymath 🌌",
  "js.arquitecto_de_ideas": "Idea Architect 🏛️",
  "js.analista_sintetico": "Synthetic Analyst 🔭",
  "js.cargando_tu_proyecto": "Loading your project...",
  "js.no_se_pudo_cargar": "Could not load",
  "js.error_al_abrir_el_proyecto": "Error opening the project.",
  "js.deseas_iniciar_un_esquema_completamente": "Do you want to start a completely blank map in a separate project?",
  "js.no_se_pudo_cargar_el": "Could not load the PayPal SDK.",
  "js.comprar_nodos": "buy nodes",
  "js.no_se_pudo_iniciar_la": "Could not start the purchase. Try again.",
  "js.no_se_pudo_confirmar_el": "Could not confirm the payment. If you were charged, write to us so we can credit your nodes.",
  "js.exito_se_han_anadido_nodos": "Success! {nodesAdded} nodes have been added to your account.",
  "js.ocurrio_un_problema_con_paypal": "There was a problem with PayPal. Try again in a moment.",
  "js.realizar_peticiones_personalizadas": "make custom requests",
  "js.desarrollando_tu_peticion": "Working on your request...",
  "js.no_se_pudo_procesar_tu": "Could not process your request.",
  "js.peticion": "*✨ Request:*\n\"{customRequest}\"",
  "js.consulta": "query",
  "js.explorar_antitesis_y_pensamiento_critico": "explore antitheses and critical thinking",
  "js.buscando_contradicciones_y_limites_teoricos": "Looking for contradictions and theoretical limits...",
  "js.no_se_pudo_generar_la_2": "Could not generate the antithesis.",
  "js.error_al_generar_antitesis": "Error generating antithesis.",
  "js.reto_socratico": "🧠 Socratic Challenge: {topicName}",
  "js.escribe_una_respuesta_breve_para": "Write a short answer to be evaluated.",
  "js.evaluando_tu_argumento": "Evaluating your argument...",
  "js.no_se_pudo_evaluar_tu": "Could not evaluate your answer.",
  "js.tu_sintesis_retroalimentacion": "Your synthesis: \"{userAnswer}\"\n\nFeedback: {feedback}",
  "js.sintesis_propia": "own synthesis",
  "js.error_al_evaluar": "Error evaluating.",
  "js.activar_el_reto_socratico": "activate the Socratic challenge",
  "js.formulando_desafio_socratico": "Formulating Socratic challenge...",
  "js.no_se_pudo_iniciar_el": "Could not start the challenge.",
  "js.error_al_iniciar_el_reto": "Error starting the challenge.",
  "js.esquema": "Map",
  "js.definicion": "Definition",
  "js.explicacion_sencilla": "Simple explanation",
  "js.analogia": "Analogy",
  "js.ejemplos_practicos": "Practical examples",
  "js.todavia_no_hay_un_esquema": "There is no map to make a report from yet.",
  "js.de_nodos_todavia_no_tienen": "{missing} of {total} nodes don't have a definition or simple explanation yet. ",
  "js.si_las_generas_se_usan": "If you generate them, the same services (and the same balance) are used as when opening them one by one from each node. ",
  "js.si_no_el_informe_incluye": "If not, the report includes only what already exists.",
  "js.armar_el_informe": "Build the report",
  "js.generar_lo_que_falta": "Generate what's missing ({missing})",
  "js.solo_lo_que_ya_existe": "Only what already exists",
  "js.preparando_el_contenido_del_informe": "Preparing the report content (0 of {missing})…",
  "js.preparando_el_contenido_del_informe_2": "Preparing the report content ({done} of {missing})…",
  "def.simple_words": "In simple words",
  "def.its_like": "🔗 It's like...",
  "def.for_example": "For example",
  "def.writing": "Writing the definition…",
  "def.preparing_simple": "Preparing a simple explanation…",
  "def.err_get": "Could not get the definition.",
  "def.err_get_generic": "Error getting the definition.",
  "def.err_simple": "Could not generate the explanation.",
  "def.err_simple_generic": "Error generating the explanation.",
  "def.source": "Source",
  "def.hint": "💡 Click the concepts highlighted with ⚡ to add them to the map.",
  "onb.no_area": "No area matches your search.",
  "aprende.abriendo": "Opening your map…",
  "coach.t_node": "Tap this node",
  "coach.b_node": "Each node is an idea from your text. Tap it to see everything you can do with it.",
  "coach.t_explain": "Ask for the simple version",
  "coach.b_explain": "It explains it as if you knew nothing about the topic. It is free.",
  "coach.t_mark": "Tap an underlined passage",
  "coach.b_mark": "It takes you to the node that idea came from: the text and the map stay connected.",
  "coach.t_node2": "Now tap another node",
  "coach.b_node2": "Each one has its own menu. Try another.",
  "coach.t_def": "See the definition",
  "coach.b_def": "Opens a panel with the concept definition, with its source. Also free.",
  "coach.t_grow": "Grow your map",
  "coach.b_grow": "Add related concepts, examples, antitheses and more. Each one adds nodes to the map.",
  "coach.t_done": "That is all for now",
  "coach.b_done": "The map is yours: explore it, edit it and drag the nodes. We will not show this tour again.",
  "coach.skip": "Skip tour",
  "coach.next": "Next ›",
  "coach.finish": "Got it",
  "search.no_results": "No results.",
  "gaps.generate": "Generate a map for this →",
  "gaps.none": "No gaps to show.",
  "proj.last_saved": "Last saved",
  "proj.current": "Current",
  "proj.open": "Open",
  "tour.end": "End of the tour",
  "tour.visited_one": "You visited 1 place in the map.",
  "tour.visited_many": "You visited {n} places in the map.",
  "tour.like": "Like {analogy}",
  "quiz.question_of": "Question {i} of {n}",
  "quiz.what_is": "What is “{title}”?",
  "quiz.think": "Think of your answer before revealing it.",
  "quiz.show_answer": "Show answer",
  "quiz.knew": "✓ I knew it",
  "quiz.didnt_know": "✗ I didn't know it",
  "quiz.done": "Quiz finished",
  "quiz.score": "You knew {ok} of {total} ({pct}%)",
  "quiz.retry": "Retry",
  "toast.link_suggest": "💡 \"{a}\" and \"{b}\" appear very close together in the text. Link them?",
  "toast.link": "Link",
  "toast.dismiss": "Dismiss",
  "panel.link_title": "Join to another node or panel with an arrow",
  "panel.minimize": "Minimize",
  "panel.close": "Close",
  "soc.challenge": "Comprehension Challenge",
  "soc.placeholder": "Write your reasoning or argument here...",
  "soc.submit": "Validate my Reasoning (+Mastery Node)",
  "soc.verdict": "🌟 Verdict:",
  "rpt.generated": "Report generated with Graphikosmos",
  "rpt.no_definition": "No definition generated yet.",
  "edge.related": "related",
  "ui.ph_mobile_paste": "Paste a text, a topic, or a web page link here...",
  "ui.ph_onb_question": "E.g.: Why did it happen that way? How is it different from...?",
  "ui.ph_onb_source": "Paste a text or a page link here...",
  "ui.ph_feedback": "Tell us what you came up with, what didn't work, or what you'd like the app to do..."
};
